# Generated by Django 3.0.4 on 2020-09-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='desciption',
            new_name='description',
        ),
    ]
