# Generated by Django 3.0.4 on 2020-09-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_auto_20200907_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
