# Generated by Django 3.0.4 on 2020-09-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiredate',
            field=models.DateField(max_length=40),
        ),
        migrations.AlterField(
            model_name='member',
            name='joindate',
            field=models.DateField(max_length=40),
        ),
    ]
